server:
  port: 80
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://121.5.160.142:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml